name: 'PixiJS Benchmark'
description:
  'Run PixiJS performance benchmarks via Playwright and compare to baseline'
inputs:
  benchmark-path:
    description: 'Path to the folder containing the benchmarks'
    required: true
  perf-change:
    description: The acceptable percentage difference allowed
    required: false
    default: '5'
runs:
  using: 'node24'
  main: 'src/index.js'
